import type { Metadata } from "next";
import { PageHero } from "@/components/sections/page-hero";
import { CtaSection } from "@/components/sections/cta-section";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "About Us", description: "Learn about New York S. Storage, a Manhattan storage facility founded in 1975 and located in Harlem.", alternates: { canonical: "/about-us/" } };
export default function AboutPage() { return <><PageHero eyebrow="About New York S. Storage" title="Making room for New Yorkers since 1975" description="A clean, friendly, secure Harlem storage facility built around practical advice and flexible space." />
  <section className="section content-section"><div className="shell service-overview"><div><p className="eyebrow">Our story</p><h2>Experience you can feel in the details.</h2><p>New York S. Storage is Manhattan’s premier storage facility, founded in 1975. We provide a clean, friendly, and secure environment for personal belongings, household furniture, business materials, and specialty items.</p><p>Our storage advisors are here to answer questions, help estimate space, and make the process more manageable—whether you need one compact unit or room for a larger move.</p></div><div className="service-visual"><span style={{fontSize:"8rem",fontWeight:800,color:"var(--green-700)",letterSpacing:"-.08em",position:"relative"}}>1975</span><div className="service-visual-badge"><span>One Harlem location</span>Decades of storage experience</div></div></div></section>
  <section className="section"><div className="shell"><SectionHeading eyebrow="What matters here" title="Straightforward storage, thoughtfully run" /><div className="feature-grid">{[{t:"Clean space",d:"Maintained, well-lit floors for a better storage experience."},{t:"Practical guidance",d:"Advisors who help you think through size, timing, and moving needs."},{t:"Flexible plans",d:"Short- and long-term options for changes both planned and unexpected."},{t:"Local access",d:"A Harlem facility close to subway lines and major routes."}].map((item,index)=><article className="feature-card" key={item.t}><span className="feature-number">0{index+1}</span><h3>{item.t}</h3><p>{item.d}</p></article>)}</div></div></section><CtaSection title="Come talk storage with us" /></> }

