import type { Metadata } from "next";
import { PageHero } from "@/components/sections/page-hero";
import { site } from "@/data/site";

export const metadata: Metadata = { title: "Terms & Privacy", description: "Privacy and data-use information for New York S. Storage website visitors and customers.", alternates: { canonical: "/terms-conditions/" } };
export default function TermsPage() { return <><PageHero eyebrow="Terms & privacy" title="How we handle your information" description="This policy explains the information New York S. Storage may collect, why it is used, and the choices available to you." compact /><section className="section content-section"><article className="shell content-narrow prose"><p><strong>Effective March 16, 2026.</strong></p>
  <h2>Privacy policy</h2><p>This policy applies to newyorksstorage.com and New York S. Storage. By using this website, you consent to the data practices described here. New York S. Storage does not sell or rent its customer lists or personal information.</p>
  <h2>Information we may collect</h2><p>We collect personal information only when you voluntarily provide it, such as when requesting a quote, contacting us, registering for an account, purchasing products or services, or communicating by email or text. This may include your name, mailing address, email address, phone number, demographic details, billing information, and details about the services you request.</p><p>We may also collect technical information such as IP address, browser type, domain name, access time, and referring website address to operate the website, maintain service quality, and understand general usage.</p>
  <h2>How information is used</h2><ul><li>To provide products, information, quotes, and services you request.</li><li>To communicate about your account, orders, storage, moving, or delivery arrangements.</li><li>To carry out contractual obligations and protect company rights.</li><li>To notify you about service or policy changes.</li><li>For other purposes described when you provide the information or with your consent.</li></ul>
  <h2>Service providers and legal requirements</h2><p>Information may be shared with trusted providers who help us deliver services, customer support, communications, statistical analysis, or deliveries. These providers may use information only to perform those services and are expected to maintain confidentiality. Information may also be disclosed when required by law, to comply with legal process, protect rights or property, or protect personal and public safety.</p>
  <h2>Security</h2><p>We use reasonable measures to protect personal information from unauthorized access, use, or disclosure. Information transmitted to other websites may be protected with SSL encryption. No internet or wireless transmission can be guaranteed to be completely secure.</p>
  <h2>Deletion requests</h2><p>You may submit a verifiable request to delete personal information. Some information may need to be retained to complete a transaction, detect or prevent security incidents and illegal activity, fix errors, comply with legal obligations, or support other lawful internal uses.</p>
  <h2>Children under 13</h2><p>New York S. Storage does not knowingly collect personally identifiable information from children under 13. Children under 13 should use this website only with permission from a parent or guardian.</p>
  <h2>Email and text communications</h2><p>From time to time, the company may contact customers by email or text regarding announcements, offers, alerts, confirmations, surveys, or general communications. Data may be stored with contracted third-party hosting vendors.</p>
  <h2>Policy changes</h2><p>We may update this policy as services, privacy practices, or laws change. Significant changes may be communicated by email, a prominent website notice, or an updated policy. Continued use after an update constitutes acknowledgment of the modified policy.</p>
  <h2>Contact information</h2><p>Questions or concerns may be directed to New York S. Storage at {site.address.street}, {site.address.city}, {site.address.region} {site.address.postalCode}; <a href={`mailto:${site.email}`}>{site.email}</a>; or <a href={site.phoneHref}>{site.phoneDisplay}</a>.</p>
  </article></section></> }

